### ISSUE TITLE
Remove dependency on TCLAP for command line parsing.

### ISSUE THREAD

**Issue by paul-g** [custom-computing-ic/hydrogen#15]
Boost already a module for parsing [command line arguments ](http://www.boost.org/doc/libs/1_49_0/doc/html/program_options.html), let's avoid adding an extra dependency if possible.

**Comment by mtottenh** [comment]
I've transitioned everything over to boost program options. we can now safely remove the commented out code in the cmake file. (All tests pass).

**Comment by paul-g** [comment]
Perfect! Thanks!
