### ISSUE TITLE
master/HEAD doesn't pass tests

### ISSUE THREAD

**Issue by mtottenh** [custom-computing-ic/hydrogen#2]
I forgot to run the tests before I pushed.

I've tagged the last commit Paul made as v0.1.

I'll work on fixing this asap

**Comment by paul-g** [comment]
OK, I'm working on the threading part right now, so I'm diverging from the current version quite a bit.

**Comment by mtottenh** [comment]
I pushed a quick fix which takes the scheduling code out of the equation.

it now runs pretty much the exact code path it did before.
